### ISSUE TITLE
Set up database

### ISSUE THREAD

**Issue by software-engr-full-stack** [software-engr-full-stack/va-services-user#1]
- Possibly use dbmate
- Possibly use PostgreSQL
- Docker or just use local database?

**Comment by software-engr-full-stack** [comment]
Done: see commit [Do no commit .env file](https://github.com/software-engr-full-stack/va-services-user/commit/88add47189bf64580423f985369123b69a892f58)

**Comment by kangkyu** [comment]
https://github.com/software-engr-full-stack/va-services-user/compare/de7edc2c374ff40a144e621b885b17dcfddb5643..88add47189bf64580423f985369123b69a892f58
